libpci: use "brute force" scan for devices
seL4/util_libs pull request #132
Opened 2022-07-19 12:42 UTC by abrandnewusername

To handle cases where PCI or PCIe buses are not accessible via
a bridge from bus 0, We use "brute force" scan instead of recursive
scan here. Details of these methods can be found on
https://wiki.osdev.org/PCI#.22Brute_Force.22_Scan.

Signed-off-by: Jingyao Zhou <jingyao.zhou@unsw.edu.au>

This is not the ideal solution, but a workaround for this issue: https://github.com/seL4/util_libs/issues/131

2022-07-19 23:18 UTC, wom-bat requested changes

2022-07-19 23:18 UTC, wom-bat commented on libpci/src/pci.c
>  {
Why not just get rid of this function, and call `libpci_add_fun()` directly from the scan?

2022-07-19 23:44 UTC, kent-mcleod commented
> This is not the ideal solution, but a workaround for this issue: #131

Would it be possible to implement this alternate scanning approach as a separate function to maintain the existing functionality for clients that already depend on it?

2022-07-20 03:55 UTC, wom-bat commented
>  Would it be possible to implement this alternate scanning approach as a separate function to maintain the existing functionality for clients that already depend on it?
The existing functionality is just an optimisation to avoid scanning everything.   The new code brute-force scans every possible bus, and will pick up any that have been configured by the BIOS.

The existing code is wrong when:
 --- some buses are not attached via bridges but have a separate root complex
 --- the BIOS doesn't enable the bus (the new code won't work for this case either)
 --- where there is more than one PCI domain.

2022-07-26 03:30 UTC, kent-mcleod commented
> The existing functionality is just an optimisation to avoid scanning everything. The new code brute-force scans every possible bus, and will pick up any that have been configured by the BIOS.

Is the brute force approach noticeably slower to execute?

2022-07-27 06:47 UTC, wom-bat commented
> Is the brute force approach noticeably slower to execute?

Not that I can tell with a single PCI domain (and we don't deal with more than a single PCI domain at the moment).
Of course, to do it properly, you'd parse the DSDT and use the full 4k config space  for each device.

2022-08-10 00:08 UTC, wom-bat approved these changes
Looks good to me now.

2022-08-10 00:08 UTC, merged